//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.MainBoundedContext.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.MainBoundedContext.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 车长不能为空 的本地化字符串。
        /// </summary>
        internal static string validation_GooderCarLengthNull {
            get {
                return ResourceManager.GetString("validation_GooderCarLengthNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车型不能为空 的本地化字符串。
        /// </summary>
        internal static string validation_GooderCarTypeNull {
            get {
                return ResourceManager.GetString("validation_GooderCarTypeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择目的地 的本地化字符串。
        /// </summary>
        internal static string validation_GooderDestCityFristNull {
            get {
                return ResourceManager.GetString("validation_GooderDestCityFristNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货物重量与体积至少填写一项 的本地化字符串。
        /// </summary>
        internal static string validation_GooderHeightAndVolumeNotAllNull {
            get {
                return ResourceManager.GetString("validation_GooderHeightAndVolumeNotAllNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货物名称不能为空 的本地化字符串。
        /// </summary>
        internal static string validation_GooderNameNotAllNull {
            get {
                return ResourceManager.GetString("validation_GooderNameNotAllNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 支付方式不能为空 的本地化字符串。
        /// </summary>
        internal static string validation_GooderPaywayNull {
            get {
                return ResourceManager.GetString("validation_GooderPaywayNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择起始地 的本地化字符串。
        /// </summary>
        internal static string validation_GooderSourceCityNull {
            get {
                return ResourceManager.GetString("validation_GooderSourceCityNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 装卸方式不能为空 的本地化字符串。
        /// </summary>
        internal static string validation_GooderTransferwayNull {
            get {
                return ResourceManager.GetString("validation_GooderTransferwayNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货物运费为能为空 的本地化字符串。
        /// </summary>
        internal static string validation_GooderUnitPriceLetZero {
            get {
                return ResourceManager.GetString("validation_GooderUnitPriceLetZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户手机不能为空 的本地化字符串。
        /// </summary>
        internal static string validation_MobileCannotBeNull {
            get {
                return ResourceManager.GetString("validation_MobileCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户密码不能为空 的本地化字符串。
        /// </summary>
        internal static string validation_PassWordCannotBeBull {
            get {
                return ResourceManager.GetString("validation_PassWordCannotBeBull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目的城市不能为空 的本地化字符串。
        /// </summary>
        internal static string validation_ProductDriverDestCity {
            get {
                return ResourceManager.GetString("validation_ProductDriverDestCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 起始城市不能为空 的本地化字符串。
        /// </summary>
        internal static string validation_ProductDriverSoruceCity {
            get {
                return ResourceManager.GetString("validation_ProductDriverSoruceCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码不能为空 的本地化字符串。
        /// </summary>
        internal static string validation_SmsCodeNotAllNull {
            get {
                return ResourceManager.GetString("validation_SmsCodeNotAllNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证手机不能为空 的本地化字符串。
        /// </summary>
        internal static string validation_SmsMobileNull {
            get {
                return ResourceManager.GetString("validation_SmsMobileNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 专线到达城市不能为空 的本地化字符串。
        /// </summary>
        internal static string validation_SpecwayDestCityNull {
            get {
                return ResourceManager.GetString("validation_SpecwayDestCityNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 专线公司名称不能为空 的本地化字符串。
        /// </summary>
        internal static string validation_SpecwayNameNotAllNull {
            get {
                return ResourceManager.GetString("validation_SpecwayNameNotAllNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 专线城市不能为空 的本地化字符串。
        /// </summary>
        internal static string validation_SpecwaySourceCityFristNull {
            get {
                return ResourceManager.GetString("validation_SpecwaySourceCityFristNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 专线省份不能为空 的本地化字符串。
        /// </summary>
        internal static string validation_SpecwaySourcePrivinceNull {
            get {
                return ResourceManager.GetString("validation_SpecwaySourcePrivinceNull", resourceCulture);
            }
        }
    }
}
