//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistributedServices.MainBoundedContext.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DistributedServices.MainBoundedContext.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Unmanaged error in aplication, the exception information is 的本地化字符串。
        /// </summary>
        internal static string error_unmanagederror {
            get {
                return ResourceManager.GetString("error_unmanagederror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 司机无权发布专线或货源信息 的本地化字符串。
        /// </summary>
        internal static string error_ValidateCarUser {
            get {
                return ResourceManager.GetString("error_ValidateCarUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入正确的手机号 的本地化字符串。
        /// </summary>
        internal static string error_ValidateMobileFormat {
            get {
                return ResourceManager.GetString("error_ValidateMobileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您的帐号已被冻结 的本地化字符串。
        /// </summary>
        internal static string error_ValidateMobileFreeze {
            get {
                return ResourceManager.GetString("error_ValidateMobileFreeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您的手机号尚未注册 的本地化字符串。
        /// </summary>
        internal static string error_ValidateMobileNotReisterExisting {
            get {
                return ResourceManager.GetString("error_ValidateMobileNotReisterExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帐号或密码不正确 的本地化字符串。
        /// </summary>
        internal static string error_ValidateMobileOrPasswordFormat {
            get {
                return ResourceManager.GetString("error_ValidateMobileOrPasswordFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您输入的手机已注册 的本地化字符串。
        /// </summary>
        internal static string error_ValidateMobileReisterExisting {
            get {
                return ResourceManager.GetString("error_ValidateMobileReisterExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您输入的新手机与原手机号相同 的本地化字符串。
        /// </summary>
        internal static string error_ValidateNewMobileAndMobileIsEq {
            get {
                return ResourceManager.GetString("error_ValidateNewMobileAndMobileIsEq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入正确的新手机号 的本地化字符串。
        /// </summary>
        internal static string error_ValidateNewMobileFormat {
            get {
                return ResourceManager.GetString("error_ValidateNewMobileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新的手机号已存在 的本地化字符串。
        /// </summary>
        internal static string error_ValidateNewMobileReisterExisting {
            get {
                return ResourceManager.GetString("error_ValidateNewMobileReisterExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您不是管理员，无权限调用数据 的本地化字符串。
        /// </summary>
        internal static string error_ValidateNotAdmin {
            get {
                return ResourceManager.GetString("error_ValidateNotAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择上传文件 的本地化字符串。
        /// </summary>
        internal static string error_ValidateNotUpLoadFile {
            get {
                return ResourceManager.GetString("error_ValidateNotUpLoadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您目前不是VIP，没有刷新置顶权限 的本地化字符串。
        /// </summary>
        internal static string error_ValidateNotVIPReflus {
            get {
                return ResourceManager.GetString("error_ValidateNotVIPReflus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 两次输入密码不相等 的本地化字符串。
        /// </summary>
        internal static string error_ValidatePasswordAndConfirmPasswordFormat {
            get {
                return ResourceManager.GetString("error_ValidatePasswordAndConfirmPasswordFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您输入的密码与原密码相同 的本地化字符串。
        /// </summary>
        internal static string error_ValidatePasswordAndNewPasswordIsEq {
            get {
                return ResourceManager.GetString("error_ValidatePasswordAndNewPasswordIsEq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 两次输入密码不相等 的本地化字符串。
        /// </summary>
        internal static string error_ValidatePasswordAndNewPasswordNotEq {
            get {
                return ResourceManager.GetString("error_ValidatePasswordAndNewPasswordNotEq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入正确的密码，密码格式6-32字符 的本地化字符串。
        /// </summary>
        internal static string error_ValidatePasswordFormat {
            get {
                return ResourceManager.GetString("error_ValidatePasswordFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入正确的动态验证码 的本地化字符串。
        /// </summary>
        internal static string error_ValidateSmsFormat {
            get {
                return ResourceManager.GetString("error_ValidateSmsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您发送的短信太快，请休息片刻！ 的本地化字符串。
        /// </summary>
        internal static string error_ValidateSmsTimeCount {
            get {
                return ResourceManager.GetString("error_ValidateSmsTimeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传文件扩展名是不允许的扩展名 的本地化字符串。
        /// </summary>
        internal static string error_ValidateUpLoadFileNotAllowFx {
            get {
                return ResourceManager.GetString("error_ValidateUpLoadFileNotAllowFx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传文件大小超过限制 的本地化字符串。
        /// </summary>
        internal static string error_ValidateUpLoadFileTooBig {
            get {
                return ResourceManager.GetString("error_ValidateUpLoadFileTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请确认您在登录中 的本地化字符串。
        /// </summary>
        internal static string error_ValidateUserLoging {
            get {
                return ResourceManager.GetString("error_ValidateUserLoging", resourceCulture);
            }
        }
    }
}
