//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.MainBoundedContext.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.MainBoundedContext.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 添加电话记录信息不能为空 的本地化字符串。
        /// </summary>
        internal static string warning_CannotAddCallLogWithEmptyInformation {
            get {
                return ResourceManager.GetString("warning_CannotAddCallLogWithEmptyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册用户信息不能为空 的本地化字符串。
        /// </summary>
        internal static string warning_CannotAddCustomerWithEmptyInformation {
            get {
                return ResourceManager.GetString("warning_CannotAddCustomerWithEmptyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加收藏专线信息不能为空 的本地化字符串。
        /// </summary>
        internal static string warning_CannotAddFavoriteWithEmptyInformation {
            get {
                return ResourceManager.GetString("warning_CannotAddFavoriteWithEmptyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加货物信息不能为空 的本地化字符串。
        /// </summary>
        internal static string warning_CannotAddGooderProudctWithEmptyInformation {
            get {
                return ResourceManager.GetString("warning_CannotAddGooderProudctWithEmptyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加记录信息不能为空 的本地化字符串。
        /// </summary>
        internal static string warning_CannotAddMsgWithEmptyInformation {
            get {
                return ResourceManager.GetString("warning_CannotAddMsgWithEmptyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加推荐记录信息不能为空 的本地化字符串。
        /// </summary>
        internal static string warning_CannotAddPraiseWithEmptyInformation {
            get {
                return ResourceManager.GetString("warning_CannotAddPraiseWithEmptyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加短记录信息不能为空 的本地化字符串。
        /// </summary>
        internal static string warning_CannotAddSmsWithEmptyInformation {
            get {
                return ResourceManager.GetString("warning_CannotAddSmsWithEmptyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加专线信息不能为空 的本地化字符串。
        /// </summary>
        internal static string warning_CannotAddSpecwayWithEmptyInformation {
            get {
                return ResourceManager.GetString("warning_CannotAddSpecwayWithEmptyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加VIP信息不能为空 的本地化字符串。
        /// </summary>
        internal static string warning_CannotAddVipWithEmptyInformation {
            get {
                return ResourceManager.GetString("warning_CannotAddVipWithEmptyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能删除不存在的电话日志信息 的本地化字符串。
        /// </summary>
        internal static string warning_CannotRemoveNonExistingCallLog {
            get {
                return ResourceManager.GetString("warning_CannotRemoveNonExistingCallLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能删除不存在的用户信息 的本地化字符串。
        /// </summary>
        internal static string warning_CannotRemoveNonExistingCustomer {
            get {
                return ResourceManager.GetString("warning_CannotRemoveNonExistingCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能删除不存在的专线收藏信息 的本地化字符串。
        /// </summary>
        internal static string warning_CannotRemoveNonExistingFavorite {
            get {
                return ResourceManager.GetString("warning_CannotRemoveNonExistingFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能删除不存在的专线推荐信息 的本地化字符串。
        /// </summary>
        internal static string warning_CannotRemoveNonExistingPraise {
            get {
                return ResourceManager.GetString("warning_CannotRemoveNonExistingPraise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能删除不存在的货物信息 的本地化字符串。
        /// </summary>
        internal static string warning_CannotRemoveNonExistingProudct {
            get {
                return ResourceManager.GetString("warning_CannotRemoveNonExistingProudct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新用户信息不能为空 的本地化字符串。
        /// </summary>
        internal static string warning_CannotUpdateCustomerWithEmptyInformation {
            get {
                return ResourceManager.GetString("warning_CannotUpdateCustomerWithEmptyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新用户信息不存在 的本地化字符串。
        /// </summary>
        internal static string warning_CannotUpdateNonExistingCustomer {
            get {
                return ResourceManager.GetString("warning_CannotUpdateNonExistingCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新货物信息不存在 的本地化字符串。
        /// </summary>
        internal static string warning_CannotUpdateNonExistingProudct {
            get {
                return ResourceManager.GetString("warning_CannotUpdateNonExistingProudct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新短信记录信息不存在 的本地化字符串。
        /// </summary>
        internal static string warning_CannotUpdateNonExistingSms {
            get {
                return ResourceManager.GetString("warning_CannotUpdateNonExistingSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新发专线信息不存在 的本地化字符串。
        /// </summary>
        internal static string warning_CannotUpdateNonExistingSpecway {
            get {
                return ResourceManager.GetString("warning_CannotUpdateNonExistingSpecway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新VIP信息不能为空 的本地化字符串。
        /// </summary>
        internal static string warning_CannotUpdateNonExistingVIP {
            get {
                return ResourceManager.GetString("warning_CannotUpdateNonExistingVIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新货物信息不能为空 的本地化字符串。
        /// </summary>
        internal static string warning_CannotUpdateProudctWithEmptyInformation {
            get {
                return ResourceManager.GetString("warning_CannotUpdateProudctWithEmptyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新短信记录信息不能为空 的本地化字符串。
        /// </summary>
        internal static string warning_CannotUpdateSmsWithEmptyInformation {
            get {
                return ResourceManager.GetString("warning_CannotUpdateSmsWithEmptyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新专线信息不存在 的本地化字符串。
        /// </summary>
        internal static string warning_CannotUpdateSpecwayWithEmptyInformation {
            get {
                return ResourceManager.GetString("warning_CannotUpdateSpecwayWithEmptyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新VIP信息不能为空 的本地化字符串。
        /// </summary>
        internal static string warning_CannotUpdateVipWithEmptyInformation {
            get {
                return ResourceManager.GetString("warning_CannotUpdateVipWithEmptyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数异常 的本地化字符串。
        /// </summary>
        internal static string warning_InvalidArgumentsForFindCallLogs {
            get {
                return ResourceManager.GetString("warning_InvalidArgumentsForFindCallLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数异常 的本地化字符串。
        /// </summary>
        internal static string warning_InvalidArgumentsForFindFavorites {
            get {
                return ResourceManager.GetString("warning_InvalidArgumentsForFindFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数异常 的本地化字符串。
        /// </summary>
        internal static string warning_InvalidArgumentsForFindGooderProudcts {
            get {
                return ResourceManager.GetString("warning_InvalidArgumentsForFindGooderProudcts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数异常 的本地化字符串。
        /// </summary>
        internal static string warning_InvalidArgumentsForFindLoginLogs {
            get {
                return ResourceManager.GetString("warning_InvalidArgumentsForFindLoginLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数异常 的本地化字符串。
        /// </summary>
        internal static string warning_InvalidArgumentsForFindProudcts {
            get {
                return ResourceManager.GetString("warning_InvalidArgumentsForFindProudcts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数异常 的本地化字符串。
        /// </summary>
        internal static string warning_InvalidArgumentsForFindSmss {
            get {
                return ResourceManager.GetString("warning_InvalidArgumentsForFindSmss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数异常 的本地化字符串。
        /// </summary>
        internal static string warning_InvalidArgumentsForFindSpecways {
            get {
                return ResourceManager.GetString("warning_InvalidArgumentsForFindSpecways", resourceCulture);
            }
        }
    }
}
